# Generated by Django 5.1 on 2026-02-10 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('credits', models.DecimalField(decimal_places=1, max_digits=4)),
                ('lecturer', models.CharField(blank=True, max_length=200)),
                ('semester', models.IntegerField(default=1)),
                ('academic_year', models.CharField(default='2025/26', max_length=10)),
                ('students', models.ManyToManyField(blank=True, related_name='enrolled_modules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='modules.module')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('slides', 'Slides'), ('worksheet', 'Worksheet'), ('recording', 'Recording'), ('other', 'Other')], max_length=20)),
                ('url', models.URLField(blank=True)),
                ('available', models.BooleanField(default=True)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='modules.week')),
            ],
        ),
    ]
