# Generated by Django 4.2.28 on 2026-03-07 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_module_department_module_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('url', models.URLField(blank=True)),
                ('degree_level', models.CharField(choices=[('BSc', 'BSc'), ('MEng', 'MEng'), ('MSc', 'MSc'), ('BA', 'BA')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ModuleCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('is_compulsory', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_courses', to='modules.course')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_courses', to='modules.module')),
            ],
            options={
                'unique_together': {('module', 'course')},
            },
        ),
    ]
