# Generated by Django 4.2.28 on 2026-03-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_course_modulecourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='degree_level',
            field=models.CharField(choices=[('BSc', 'BSc'), ('MEng', 'MEng'), ('MSc', 'MSc'), ('BA', 'BA'), ('BEng', 'BEng'), ('LLB', 'LLB')], max_length=10),
        ),
    ]
