# Generated by Django 5.1 on 2026-03-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0004_add_beng_llb_degree_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='year_1_weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='year_2_weight',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='course',
            name='year_3_weight',
            field=models.IntegerField(default=70),
        ),
    ]
