# Generated by Django 5.1 on 2026-03-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0005_course_year_1_weight_course_year_2_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='year_4_weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='year_5_weight',
            field=models.IntegerField(default=0),
        ),
    ]
