# Generated by Django 5.1 on 2026-04-19 19:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_submission'),
        ('modules', '0006_course_year_4_weight_course_year_5_weight'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['module', 'due_date'], name='grades_assi_module__a0cef4_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['student', 'assignment'], name='grades_grad_student_2f954e_idx'),
        ),
    ]
