# Generated by Django 4.2.28 on 2026-03-07 15:09

from django.db import migrations, models
import django.db.models.deletion


def clear_old_course_strings(apps, schema_editor):
    """Wipe the old CharField data so the FK migration doesn't break."""
    UserProfile = apps.get_model('accounts', 'UserProfile')
    UserProfile.objects.all().update(course=None)


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_course_modulecourse'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        # First null out old string values so they don't clash with the new FK
        migrations.AlterField(
            model_name='userprofile',
            name='course',
            field=models.CharField(max_length=200, blank=True, null=True),
        ),
        migrations.RunPython(clear_old_course_strings, migrations.RunPython.noop),
        # Now convert to FK
        migrations.AlterField(
            model_name='userprofile',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='modules.course'),
        ),
    ]
