# Generated by Django 5.1 on 2026-04-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='degree_level',
            field=models.CharField(choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate')], default='UG', max_length=2),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='student_id',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='university',
            field=models.CharField(choices=[('UOL', 'University of Liverpool'), ('LJMU', 'Liverpool John Moores University'), ('HOPE', 'Liverpool Hope University')], default='UOL', max_length=10),
        ),
    ]
