# Generated by Django 5.1 on 2026-04-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_student_id_study_level_university_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='registration_complete',
            field=models.BooleanField(default=True),
        ),
    ]
