# Generated by Django 5.1 on 2026-02-23 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableentry',
            name='semester',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='weeks',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
