# Generated by Django 5.1 on 2026-04-19 19:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0006_course_year_4_weight_course_year_5_weight'),
        ('timetable', '0002_timetableentry_semester_timetableentry_weeks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['student', 'semester'], name='timetable_t_student_998b19_idx'),
        ),
    ]
